### ISSUE TITLE
Cancel active order

### ISSUE THREAD

**Issue by sbralin** [krijnsent/crypto_vba#36]
Hi, I am trying to cancel active order (i got orderId) on binance and I use: 
Debug.Print PrivateBinance("order", apikey, secretkey, "symbol=ICXBTC&orderId=25200510")
but I got error {"code":-1102,"msg":"Mandatory parameter 'side' was not sent, was empty/null, or malformed."}. Pls, help me.
Thanks 
Saga

**Comment by krijnsent** [comment]
Hi Saga,
Did you check out the binance API page? ( https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md ) Instead of a POST command you'd have to send a DELETE command. Something I didn't build into my vba code yet. I have it on my to do, but will be busy with other stuff in the coming period. Hope that pointer helps you solving the issue?

**Comment by sbralin** [comment]
Thanks I have done it!
