### ISSUE TITLE
File crypto_vba_example.xlsm triggers Defender

### ISSUE THREAD

**Issue by cmseasy** [krijnsent/crypto_vba#67]
File crypto_vba_example.xlsm triggers my virusscanner (Defender, default Windows10) detecting: Trojan:Script/Oneeva.A!ml and removes the file to quarantaine. Please check.

**Comment by krijnsent** [comment]
Mmm, that's weird. It doesn't trigger on my Win 10 PC with AVG . I checked it online with virustotal: https://www.virustotal.com/gui/file/072f61240a2b1dbff8869178ccf7d348c416ff1adb02e5de883c0c2d61958760/detection -> there are apparently 5 virusscanners that state my xlsm has something dangerous in it although I know there is nothing there.
I'll check if I can find something, otherwise you'd have to import the .bas modules yourself.

I also checked my other crypto file: https://github.com/krijnsent/my_wallets_vba/blob/master/wallets_vba_example.xlsm -> that one gets detected by 3 engines ( https://www.virustotal.com/gui/file/33e9d5072f65ebae3f0f29b4a6c50c2abc17e8e2c846a13f5526b3e446307791/detection ). No clue what to do it to be honoust...

**Comment by cmseasy** [comment]
I saw the commant on https://www.virustotal.com/gui/file/072f61240a2b1dbff8869178ccf7d348c416ff1adb02e5de883c0c2d61958760/community

Maybe a false positive detection because of the suspicious behavoir of the macro's in the sheet. But how do we know for sure? And how to get rid of the virus report in W10 Defence; ignoring the notification is not realy nice and safe.

**Comment by krijnsent** [comment]
I asked around, e.g. here: https://www.reddit.com/r/vba/comments/m8g4sj/self_made_excelvba_triggers_virus_scan_what_to_do/ But couldn't find anything that I can do to fix this :-(. If I find something I'll try to implement it.

**Comment by krijnsent** [comment]
I'm going to close this issue: I know it's there but can't do anything about it. I've put 2 work arounds in my readme.md
